spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vacc?useSSL=false&characterEncoding=utf-8
      username: root
      password: 123456
  web:
  webflux:
    static-path-pattern: /**
mybatis-plus:
  configuration: #如果需要在控制台输出SQL日志信息，则配置，否则删除即可
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl